server:
  port: 8080
spring:
  profiles:
    active: dev2
  mvc:
    static-path-pattern: /res/** #this is to give prefix/res and load the static resources, example localhost:8080/res/xxx
  resources:
    static-locations: classpath:/pic  #this is to defined own classpath for static resources

person:
    userName: zhangsan
    boss: false
    birth: 2019/12/12 20:12:33
    age: 18
    pet:
      name: tomcat

    interests: [篮球,游泳]
    animal: [jerry, mario]

    score:
      english:
        first: 30
        second: 40
        third: 50

      math: [131,140,148]
      chinese: {first: 128,second: 136}
    salarys: [3999,4999.98,5999.99]

    allPets:
      sick: [jerry, mario]
      health: [haha]


mycar:
  brand: BYD
  price: 100000


---

spring:
  datasource:
    #This is for local mysql
    url: jdbc:mysql://localhost:3306/springdemo?useTimezone=true&serverTimezone=UTC
    #This is for connecting docker container mysql instance for 6604:3306 port
    #url: jdbc:mysql://localhost:6604/test #-- this is something 6604:3306
    #url: jdbc:mysql://sql_container2/test # this is for docker image sql database
    username: root
    password: 61376554
    #Below is for docker mysql needed
    initialization-mode: always
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # To auto generate and created the table into the database without we created
    generate-ddl: true
    hibernate:
      ddl-auto=create:
  profiles: dev1

---

spring:
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password: 123456
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  profiles: dev2

---





