package com.test.springboot;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Application {

	// we can also use cmd to execute the jar generated by maven clean, go to the folder and java jar xxxxxx.jar
	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

}
